# Generated by Django 3.2.6 on 2021-08-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.JSONField()),
                ('source_url', models.URLField()),
                ('output_text', models.JSONField()),
            ],
        ),
    ]
