# Generated by Django 3.2.6 on 2021-08-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dead_south', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.TextField(default='title'),
        ),
    ]
