# Generated by Django 3.2.6 on 2021-08-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dead_south', '0003_article_dead_south__source__23a7ac_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
